# -*- coding: utf-8 -*-
"""Data Scanner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16naFFQTT9MA7QaJNQAsHM9ViqZFC114F
"""

# STEP 1: Install required libraries
!pip install pandas matplotlib seaborn scikit-learn

# STEP 2: Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from google.colab import files

# STEP 3: Upload your own dataset (CSV only)
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
df.columns = df.columns.str.strip()  # remove any trailing spaces
df.head()

#STEP 4: Basic Summary Report
print("DATA SUMMARY REPORT")
print(f" Rows: {df.shape[0]} | Columns: {df.shape[1]}")
print("\n Column Types:")
print(df.dtypes)

print("\n Missing Values:")
print(df.isnull().sum())

print("\n Basic Stats (Numerical Columns):")
print(df.describe().T)